tap_install:
    sensitive_values:
        shared:
            ingress_domain: ENC[AES256_GCM,data:FYsidKk15vNgw3zDPxBaw/6QEzMEFyMk8fvlmhlQvAAuElh+I52qsQglYsY=,iv:rJBG8CmhglftjaOI2We4Tszb2C2sMWpt1xF6X4eg+rQ=,tag:rm+KTN24t6as/zxnSWGeOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140kfw9jqh7d63svrgf8rpjaf8mteg507va4s98pnjtl975qe6stqfpaxvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSTlKWGZsRFhQQ2RhRGIv
            WmRNbDJuUjdqbTFRb1NkV1BNODVFZS9PSWpnCjNjQU56U1lUYjBqQXUyTW9oTW8z
            dU9ZZE5yT0tHRlpFY0RlOERXKy80eGMKLS0tIGwvYzc4aTgyMVB4WjNTWk00eVFX
            eDVWMUZuNCtsaEUzVkF0dU5HcXR6WFkKXVWqqwqQYPNJDNMOA3i7du84TYgMjr3F
            8c0qAmeGcjgT2kKgg0sGBFEEWcShBVjGkSh7q/aIPNa7QsNR/8PbHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-20T07:13:55Z"
    mac: ENC[AES256_GCM,data:g62Vi2ju/l3G8La7iH/F8Nxk4zzkpXu+twdVrcPVirFMSPVZPLkFkV0AV+TdbsJJ4qKTlK9Y9Om1JunQqHnW+Inlh2tlzYQ0iW7cpJuhKaACtvdVPb9weJbLhmcQ81Xn/gD4GooG5FPJ1YN4F9QFBVRyYRjGhLX1HskQZzMIciA=,iv:ICrPh3uu/x77NtalN9ijz3Jz6TahnIPPIIJumG105+g=,tag:GS47SMH5WYnPI1++WBcd0Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
